stem: CWE121_Stack_Based_Buffer_Overflow__CWE805_char_declare_memcpy_01
cwe: 121
segment: STACK
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE121_Stack_Based_Buffer_Overflow__CWE805_char_declare_memcpy_01_bad
  good: null
