stem: CWE484_Omitted_Break_Statement_in_Switch__basic_01
cwe: 484
segment: DATA
effect: READ
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE484_Omitted_Break_Statement_in_Switch__basic_01_bad
  good: null
