stem: CWE191_Integer_Underflow__int_min_sub_01
cwe: 191
segment: DATA
effect: TRIGGER
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE191_Integer_Underflow__int_min_sub_01_bad
  good: null
