stem: CWE321_Hard_Coded_Cryptographic_Key__w32_char_01
cwe: 321
segment: STACK
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE321_Hard_Coded_Cryptographic_Key__w32_char_01_bad
  good: null
