stem: CWE562_Return_of_Stack_Variable_Address__return_buf_01
cwe: 562
segment: DATA
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE562_Return_of_Stack_Variable_Address__return_buf_01_bad
  good: null
