stem: CWE415_Double_Free__malloc_free_wchar_t_01
cwe: 415
segment: HEAP
effect: READ
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE415_Double_Free__malloc_free_wchar_t_01_bad
  good: null
