stem: CWE190_Integer_Overflow__int_max_add_01
cwe: 190
segment: DATA
effect: TRIGGER
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE190_Integer_Overflow__int_max_add_01_bad
  good: null
