stem: CWE78_OS_Command_Injection__char_console_popen_01
cwe: 78
segment: DATA
effect: EXEC
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE78_OS_Command_Injection__char_console_popen_01_bad
  good: null
