stem: CWE416_Use_After_Free__malloc_free_char_01
cwe: 416
segment: HEAP
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE416_Use_After_Free__malloc_free_char_01_bad
  good: null
