stem: CWE197_Numeric_Truncation_Error__int_fscanf_to_short_01
cwe: 197
segment: DATA
effect: TRIGGER
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE197_Numeric_Truncation_Error__int_fscanf_to_short_01_bad
  good: null
