stem: CWE126_Buffer_Overread__malloc_char_memcpy_01
cwe: 126
segment: HEAP
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE126_Buffer_Overread__malloc_char_memcpy_01_bad
  good: null
