stem: CWE587_Assignment_of_Fixed_Address_to_Pointer__basic_01
cwe: 587
segment: DATA
effect: READ
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE587_Assignment_of_Fixed_Address_to_Pointer__basic_01_bad
  good: null
