stem: CWE114_Process_Control__w32_char_console_02
cwe: 114
segment: DATA
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE114_Process_Control__w32_char_console_02_bad
  good: null
