stem: CWE194_Unexpected_Sign_Extension__negative_memcpy_01
cwe: 194
segment: STACK
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE194_Unexpected_Sign_Extension__negative_memcpy_01_bad
  good: null
