stem: CWE127_Buffer_Underread__malloc_char_memcpy_01
cwe: 127
segment: HEAP
effect: WRITE
io: STDIN
env_key: null
file_name: null
entrypoints:
  bad: CWE127_Buffer_Underread__malloc_char_memcpy_01_bad
  good: null
